/*! uyac2.3 updated in 2016-12-02 */
define(function (require, exports, module) {
    function setJspath(obj, mainView) {
        for (var i in obj)!function (i) {
            htmlBindJs(i, obj[i], mainView)
        }(i)
    }

    function htmlBindJs(dataPage, jsPath, mainView) {
        myApp.onPageInit(dataPage, function (page) {
            require.async(jsPath, function (pageTo) {
                pageTo.pageInit(page, mainView)
            })
        })
    }

    var rootpath = (require("$"), "/js/controller/");
    exports.router = function (mainView) {
        var obj = {
            uyacProduct: rootpath + "uyac-product.js",
            productCategories: rootpath + "productCategories.js",
            "uyac-mine": rootpath + "uyac-mine.js",
            "uyac-login": rootpath + "uyac-login.js",
            "quick-login": rootpath + "quick-login.js",
            "contact-service": rootpath + "contact-service.js",
            "uyac-search": rootpath + "uyac-search.js",
            "search-result": rootpath + "uyac-search-result.js",
            "SMS-verification": rootpath + "SMS-verification.js",
            "product-detail": rootpath + "product-detail.js",
            "product-yh-detail": rootpath + "product-yh-detail.js",
            "product-yh-tw": rootpath + "product-yh-tw.js",
            "store-main": rootpath + "store-main.js",
            "address-choose": rootpath + "address-choose.js",
            "address-manager": rootpath + "address-manager.js",
            "address-edit": rootpath + "address-edit.js",
            "identityCard-add": rootpath + "identityCard-add.js",
            "identityCard-manager": rootpath + "identityCard-manager.js",
            cart: rootpath + "cart.js",
            "order-list": rootpath + "order-list.js",
            orderDetail: rootpath + "orderDetail.js",
            "order-submit": rootpath + "order-submit.js",
            logisticsRecord: rootpath + "logisticsRecord.js",
            comment: rootpath + "comment.js",
            applicationForRturn: rootpath + "applicationForRturn.js",
            fillReturnLogistics: rootpath + "fillReturnLogistics.js",
            consultRefund: rootpath + "consultRefund.js",
            resultOfPayment: rootpath + "resultOfPayment.js",
            remittanceInfo: rootpath + "remittanceInfo.js",
            "mine-info": rootpath + "mine-info.js",
            modifyNickName: rootpath + "modifyNickName.js",
            verified: rootpath + "verified.js",
            boundPhone: rootpath + "boundPhone.js",
            setPassword: rootpath + "setPassword.js",
            bindMail: rootpath + "bindMail.js",
            modifyPassword: rootpath + "modifyPassword.js",
            modifyEmail: rootpath + "modifyEmail.js",
            myWealth: rootpath + "myWealth.js",
            credits: rootpath + "credits.js",
            withdrawalsRecord: rootpath + "withdrawalsRecord.js",
            integrationModule: rootpath + "integrationModule.js",
            expenditurePoints: rootpath + "expenditurePoints.js",
            frozenPoints: rootpath + "frozenPoints.js",
            applyWithdrawals: rootpath + "applyWithdrawals.js",
            addBankCard: rootpath + "addBankCard.js",
            myBankCard: rootpath + "myBankCard.js",
            "service-submit": rootpath + "service-submit.js",
            selectBank: rootpath + "selectBank.js",
            bindIdCard: rootpath + "bindIdCard.js",
            refundSale: rootpath + "refundSale.js",
            coupon: rootpath + "coupon.js",
            shippingDescription: rootpath + "shippingDescription.js",
            membersPrivilege: rootpath + "membersPrivilege.js",
            "more-info": rootpath + "more-info.js",
            memberIntroduction: rootpath + "memberIntroduction.js",
            bindInvitationCode: rootpath + "bindInvitationCode.js",
            myCollection: rootpath + "myCollection.js",
            "product-yx-detail": rootpath + "product-yx-detail.js",
            "register-message": rootpath + "register-message.js",
            resetPassword: rootpath + "resetPassword.js",
            "email-reset": rootpath + "email-reset.js",
            "all-review": rootpath + "all-review.js",
            allComment: rootpath + "allComment.js",
            "quick-pay-list": rootpath + "quick-pay-list.js",
            "quick-pay-detail": rootpath + "quick-pay-detail.js",
            "quick-pay-submit": rootpath + "quick-pay-submit.js",
            "quick-pay-instr": rootpath + "quick-pay-instr.js",
            "store-introduce": rootpath + "store-introduce.js",
            "yaLive-Categories": rootpath + "yaLive-Categories.js",
            "yxLive-Categories": rootpath + "yxLive-Categories.js",
            "special-topic-one": rootpath + "special-topic-one.js",
            "special-topic-two": rootpath + "special-topic-two.js",
            "special-topic-three": rootpath + "special-topic-three.js",
            "special-topic-four": rootpath + "special-topic-four.js",
            giftsGategory: rootpath + "giftsGategory.js",
            "giftsGategory-detail": rootpath + "giftsGategory-detail.js",
            refundList: rootpath + "refundList.js",
            returnDetail: rootpath + "returnDetail.js",
            "share-download": rootpath + "share-download.js",
            bankPay: rootpath + "bankPay.js",
            redEnvelopeBack: rootpath + "redEnvelopeBack.js",
            newGift: rootpath + "newGift.js",
            receiveRedEnvelope: rootpath + "receiveRedEnvelope.js",
            redExpired: rootpath + "redExpired.js",
            shareRedResult: rootpath + "shareRedResult.js",
            newRedEnvelop: rootpath + "newRedEnvelop.js",
            "redPacket-newGiftCode": rootpath + "redPacket-newGiftCode.js",
            "redPacket-newGiftResult": rootpath + "redPacket-newGiftResult.js",
            "redPacket-share": rootpath + "redPacket-share.js",
            "redPacket-regit": rootpath + "redPacket-regit.js",
            "redPacket-sendMsg": rootpath + "redPacket-sendMsg.js",
            "redPacket-result": rootpath + "redPacket-result.js",
            "redPacket-overdue": rootpath + "redPacket-overdue.js",
            businessInvite: rootpath + "businessInvite.js",
            "quick-pay-merchantList": rootpath + "quick-pay-merchantList.js",
            applicableGoods: rootpath + "applicableGoods.js",
            setUp: rootpath + "setUp.js",
            personalSetting: rootpath + "personalSetting.js",
            accountSecurity: rootpath + "accountSecurity.js",
            yaLiveCoupons: rootpath + "yaLiveCoupons.js",
            myWealthList: rootpath + "myWealthList.js",
            "act-fatherDay": rootpath + "activity/act-fatherDay.js",
            "act-seaWorld": rootpath + "activity/act-seaWorld.js",
            "act-wheel": rootpath + "activity/act-wheel.js",
            "act-acceptThePrize": rootpath + "activity/act-accpetThePrize.js",
            flashSale: rootpath + "flashSale.js",
            "invite-friend": rootpath + "invite-friend.js",
            "invite-friendlist": rootpath + "invite-friendlist.js",
            redHomeNetwork: rootpath + "redHomeNetwork.js",
            myFans: rootpath + "myFans.js",
            "invite-friendlist": rootpath + "invite-friendlist.js",
            starNet: rootpath + "starNet.js",
            interestedPerson: rootpath + "interestedPerson.js",
            interestedPerson: rootpath + "interestedPerson.js",
            redNetDetails: rootpath + "redNetDetails.js",
            redNetComment: rootpath + "redNetComment.js",
            redNetDetails: rootpath + "redNetDetails.js",
            focused_person: rootpath + "focused_person.js",
            rednetList: rootpath + "rednetList.js",
            rednetSearch: rootpath + "rednetSearch.js",
            "more-rednetlist": rootpath + "more-rednetlist.js",
            "redNet-signature": rootpath + "redNet-signature.js",
            "more-rednetlist": rootpath + "more-rednetlist.js",
            redNetInfo: rootpath + "redNetInfo.js",
            getWelfare: rootpath + "getWelfare.js",
            redNetInfo: rootpath + "redNetInfo.js",
            "activityTpl-1": rootpath + "activityTpl-1.js",
            "getWelfare-code": rootpath + "getWelfare-code.js",
            "getWelfare-share": rootpath + "getWelfare-share.js",
            "getWelfare-expired": rootpath + "getWelfare-expired.js"
        };
        setJspath(obj, mainView)
    }
});